repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: lint
        name: Run linting
        language: system
        entry: just check-lint
        pass_filenames: false # `just` would try to run passed files as recipes
        stages:
          - "commit"
          - "push"
        types:
          - file
          - python
  - repo: local
    hooks:
      - id: check-formatting
        name: Check formatting
        language: system
        entry: just check-format
        pass_filenames: false # `just` would try to run passed files as recipes
        stages:
          - "commit"
          - "push"
        types:
          - file
          - python
  - repo: local
    hooks:
      - id: run-typecheck
        name: Run type checks
        language: system
        entry: just check-types
        pass_filenames: false # `just` would try to run passed files as recipes
        stages:
          - "commit"
          - "push"
        types:
          - file
          - python
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        language: system
        entry: just test
        pass_filenames: false # `just` would try to run passed files as recipes
        stages:
          - "commit"
          - "push"
        types:
          - file
          - python
