name: "Tests"
on: push

jobs:
  run:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.0
      - name: Set up virtual environment
        run: poetry install
      - name: Run tests
        run: make tests
      - name: Run type checks
        run: make typecheck
